services:
  runner:
    build: .
    restart: unless-stopped
    volumes:
      - runner_data:/runner/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner/data

volumes:
  runner_data:
