name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint-shellcheck:
    uses: yamnish/platform-ci/.github/workflows/lint-shellcheck.yml@main

  lint-hadolint:
    uses: yamnish/platform-ci/.github/workflows/lint-hadolint.yml@main

  lint-yamllint:
    uses: yamnish/platform-ci/.github/workflows/lint-yamllint.yml@main

  lint-json:
    uses: yamnish/platform-ci/.github/workflows/lint-json.yml@main

  lint-markdown:
    uses: yamnish/platform-ci/.github/workflows/lint-markdown.yml@main

  lint-gitleaks:
    uses: yamnish/platform-ci/.github/workflows/lint-gitleaks.yml@main

  lint-dotenv:
    uses: yamnish/platform-ci/.github/workflows/lint-dotenv.yml@main
