name: CI

on:
  push:
  pull_request:

jobs:
  lint-shellcheck:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-shellcheck@main

  lint-hadolint:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-hadolint@main

  lint-yamllint:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-yamllint@main

  lint-json:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-json@main

  lint-markdown:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-markdown@main

  lint-gitleaks:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yamnish/platform-ci/.github/actions/lint-gitleaks@main

  lint-dotenv:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - uses: yamnish/platform-ci/.github/actions/lint-dotenv@main
