name: Lint - gitleaks

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/lint-gitleaks
